//
// Created by UserName on 19.02.2024.
//

#ifndef VULKANRENDERENGINE_RAYTRACINGPIPELINE_HPP
#define VULKANRENDERENGINE_RAYTRACINGPIPELINE_HPP


class RayTracingPipeline {

};


#endif //VULKANRENDERENGINE_RAYTRACINGPIPELINE_H
