//
// Created by UserName on 19.02.2024.
//

#ifndef VULKANRENDERENGINE_RAYTRACINGPIPELINEBUILDER_HPP
#define VULKANRENDERENGINE_RAYTRACINGPIPELINEBUILDER_HPP


class RayTracingPipelineBuilder {

};


#endif //VULKANRENDERENGINE_RAYTRACINGPIPELINEBUILDER_H
