[package]
name = "vulkanlib"
version = "0.1.0"
edition = "2021"

[lib]
name = "vulkanlib"
path = "src/lib.rs"
crate-type = ["rlib"]

[[bin]]
name = "vulkanlib-testing"
path = "src/main.rs"


[dependencies]
ash = {version = "0.38", features = ["default", "linked", "libloading", "loaded"]}
glfw = {version = "0.60", features = ["x11", "wayland", "vulkan"]}
shaderc = "0.10"
threadpool = "1.8"