//
// Created by kgaft on 1/8/24.
//

#ifndef VULKANRENDERENGINE_SCRATCHBUFFERPOOL_HPP
#define VULKANRENDERENGINE_SCRATCHBUFFERPOOL_HPP


class ScratchBufferPool {

};


#endif //VULKANRENDERENGINE_SCRATCHBUFFERPOOL_HPP
